POST http://localhost:3333/courses
Content-Type: application/json

{
  "title": "Curso de Fastify"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/f1a8ae35-94a6-4ace-a370-54b3319a42a3